services:
    web:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./php:/var/www/html
            - ./php/img:/var/www/html/img
        env_file:
            - ./.env
        environment:
            - APP_ENV=${APP_ENV}
        depends_on:
            db:
                condition: service_healthy
            mongodb:
                condition: service_started
        restart: unless-stopped

    db:
        image: mysql:8.0
        env_file:
            - ./.env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASS}"]
            interval: 2s
            timeout: 5s
            retries: 20
            start_period: 30s
        ports:
            - "3307:3306"
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
        restart: unless-stopped

    mongodb:
        image: mongo:latest
        command: ["mongod", "--quiet", "--logpath", "/dev/null"]
        env_file:
            - ./.env
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        restart: unless-stopped

volumes:
    db_data:
    mongodb_data: